[package]
name = "openRust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio"] }
base64 = "0.21"
p256 = { version = "0.13", features = ["pkcs8"] }
pkcs8 = { version = "0.10", features = ["pem"] }
web-push = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
indexmap = { version = "2", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
maxminddb = "0.24"
bcrypt = "0.15"
woothee = "0.13"
thiserror = "2"
deadpool-redis = { version = "0.22", features = ["rt_tokio_1"] }
redis = { version = "0.32", features = ["tokio-comp"] }
altcha-lib-rs = { version = "0.3", features = ["json"] }
hmac = "0.13"
sha2 = "0.11"
chrono = "0.4"
rand = "0.10.2"
hex = "0.4.3"
